### ISSUE TITLE
Toolbox not working with block launcher

### ISSUE THREAD

**Issue by Jody24** [MCMrARM/toolbox-issue-tracker#46]
Please fill out the information below before hitting submit!
### Details

**_What did you expect to happen?**_

...the addon will work for block launcher 1.13rc1

**_What happened?**_

...It doesnt work it just said that it isnt compactible

**_When does this happen?**_

...since TB 2.0 
### Device Information

Model: _SM-G530H_

Android version: _KitKat_

Architecture: _ARM_

MC:PE version: _0.15.X_

**Comment by Jody24** [comment]
java.lang.Exception: The addon "Toolbox for Minecraft: Pocket Edition" (io.mrarm.mctoolbox) is not compatible with Minecraft PE 0.15.4.0.
    at com.mojang.minecraftpe.MainActivity.loadNativeAddons(MainActivity.java:1706)
    at com.mojang.minecraftpe.MainActivity.onCreate(MainActivity.java:377)
    at net.zhuoweizhang.mcpelauncher.LauncherAppActivity.onCreate(LauncherAppActivity.java:24)
    at android.app.Activity.performCreate(Activity.java:6609)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3243)
    at android.app.ActivityThread.access$1000(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1718)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6917)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by slice** [comment]
It looks like the addon isn't updated yet :disappointed:

**Comment by TrinityDevelopers** [comment]
Definitely.  Found this in his AndroidManifest.xml:

```
    <meta-data android:name="net.zhuoweizhang.mcpelauncher.api.nativelibname" android:value="toolbox" />
    <meta-data android:name="net.zhuoweizhang.mcpelauncher.api.targetmcpeversion" android:value="0.14.2" />
```

**Comment by TrinityDevelopers** [comment]
he most likely just needs to change that number to 0.15.4! xD

considering he runs the same library through his launcher on 0.15.4, it should run just fine.

**Comment by MCMrARM** [comment]
BlockLauncher isn't supported and I don't think it will as some stuff changed in 0.14 making TB not work in BlockLauncher most likely.

**Comment by xXHerobrinePEXx** [comment]
Please add the support for Blocklauncher because Blocklauncher has so much more possibillities for mods as your app. And it has support for new versions of texturpacks(you can import it as in vanilla) AND the good old versions.
AND its my favorite app because I'm accustomed it.
