### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#69]
### Details

***What did you expect to happen?***

I expected it to work. Well, actually I expected an unsupported version error, since I'm on the MCPE beta. But you get what I mean. 

***What happened?***

It opens to a black screen, rotated, and crashed. 

***When does this happen?***

All the time. 

### Mods/Texture Packs

What mods and or texture packs do you have installed?

None, I just installed Toolbox (and tried reinstalling).

### Logcat
```
--------- beginning of main
12-03 16:15:23.397 D/AndroidRuntime(20923): Shutting down VM
--------- beginning of crash
12-03 16:15:23.411 E/AndroidRuntime(20923): FATAL EXCEPTION: main
12-03 16:15:23.411 E/AndroidRuntime(20923): Process: io.mrarm.mctoolbox, PID: 20923
12-03 16:15:23.411 E/AndroidRuntime(20923): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.mrarm.mctoolbox/com.mojang.minecraftpe.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.mojang.minecraftpe.MainActivity" on path: DexPathList[[zip file "/data/app/io.mrarm.mctoolbox-2/base.apk"],nativeLibraryDirectories=[/data/app/io.mrarm.mctoolbox-2/lib/arm, /system/fake-libs, /data/app/io.mrarm.mctoolbox-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2586)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.os.Looper.loop(Looper.java:154)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at java.lang.reflect.Method.invoke(Native Method)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
12-03 16:15:23.411 E/AndroidRuntime(20923): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mojang.minecraftpe.MainActivity" on path: DexPathList[[zip file "/data/app/io.mrarm.mctoolbox-2/base.apk"],nativeLibraryDirectories=[/data/app/io.mrarm.mctoolbox-2/lib/arm, /system/fake-libs, /data/app/io.mrarm.mctoolbox-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
12-03 16:15:23.411 E/AndroidRuntime(20923): 	... 10 more
```

### Device Information

Model: LG G Pad 7.0 LTE (aka v410)

Android version: Nougat (Lineage for MicroG ROM)

Architecture: ARMv7

MC:PE version: 1.2.6.2 (the latest beta)

**Comment by ghost** [comment]
Possibly related to #68?

**Comment by ghost** [comment]
Update fixed it.
